"""Un second seuil, sur le score de rerank, parce que le premier ne sépare pas.

Mesuré sur le scénario HPAI (602 articles pertinents) : les articles hors sujet ont une
similarité MÉDIANE PLUS HAUTE que les articles du sujet, 0.398 contre 0.361. Monter le
curseur de similarité y jetait donc d'abord ce qu'on voulait garder. Le rerank sépare les
deux populations, 0.588 contre 0.070.

Ce que ces tests épinglent :

- la porte ne change RIEN par défaut (seuil 0, ou colonne jamais renseignée) ;
- un article sans score de rerank RESTE, là où un article sans similarité SORT. L'asymétrie
  est le coeur de la fonctionnalité : le rerank arrive par lots, et compter l'absence pour
  zéro aurait fait disparaître sans un mot les articles pas encore jugés ;
- un seuil hors de [0, 1] est refusé plutôt qu'appliqué ;
- la courbe du rerank compte les non scorés parmi ceux qui passent d'office.
"""
import pytest

pytest.importorskip("fastapi")

import main  # noqa: E402
from api.scenario_store import (  # noqa: E402
    DEFAULT_RERANK_THRESHOLD,
    relevant_gate_sql,
    scenario_rerank_threshold_sql,
)

SID = "rerank-gate"


def _engine_ok() -> bool:
    try:
        with main.engine.connect():
            return True
    except Exception:
        return False


# ─── La chaîne SQL, sans base ────────────────────────────────────────────────

def test_the_gate_mentions_both_scores():
    sql = relevant_gate_sql()
    assert "similarity_score" in sql and "rerank_score" in sql


def test_an_unscored_rerank_is_let_through_by_the_predicate_itself():
    """Lisible dans la chaîne : la seule façon de ne pas dépendre du lot en cours."""
    assert "ars.rerank_score IS NULL OR" in relevant_gate_sql()


def test_the_rerank_threshold_is_read_in_the_query_not_bound():
    """Quinze appelants partagent cette porte ; aucun n'a de `:rthr` à lier."""
    sql = relevant_gate_sql()
    assert ":rthr" not in sql
    assert "scenario_settings" in sql


def test_the_subquery_is_keyed_on_the_link_row_scenario():
    assert "ars.scenario_id" in scenario_rerank_threshold_sql("ars.scenario_id")


def test_the_default_is_zero_so_the_gate_is_unchanged():
    assert DEFAULT_RERANK_THRESHOLD == 0.0


def test_a_hand_included_article_still_bypasses_both_thresholds():
    sql = relevant_gate_sql()
    head, _, tail = sql.partition("= 'included' OR")
    assert tail, "la branche 'inclus à la main' a disparu de la porte"


# ─── La porte, contre une vraie base ─────────────────────────────────────────

@pytest.fixture()
def seeded(db_conn):
    if not _engine_ok():
        pytest.skip("main.engine cannot reach the database")
    with db_conn.cursor() as cur:
        cur.execute("DROP TABLE IF EXISTS document_search")
        cur.execute("DROP TABLE IF EXISTS document_chunk, article_scenarios, literature_document CASCADE")
        cur.execute(
            "CREATE TABLE literature_document ("
            "id bigint PRIMARY KEY, title text NOT NULL, source text NOT NULL DEFAULT 'pubmed',"
            "abstract text, year int, is_duplicate boolean DEFAULT false, screening_status text,"
            "journal text, doi text, authors text, keywords text, citation_count int,"
            "quality_score double precision, metadata_json jsonb, has_fulltext boolean,"
            "pico_json jsonb, study_design text, created_at timestamptz DEFAULT now(),"
            "project_context text DEFAULT 'literev')")
        cur.execute(
            "CREATE TABLE document_chunk ("
            "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "document_id bigint NOT NULL REFERENCES literature_document(id) ON DELETE CASCADE,"
            "chunk_index int DEFAULT 0, content text, chunk_type text, embedding text)")
        cur.execute(
            "CREATE TABLE article_scenarios (scenario_id text, document_id bigint,"
            "similarity_score double precision, rerank_score double precision,"
            "screening_status text, reviewer_1_status text, reviewer_2_status text,"
            "PRIMARY KEY (scenario_id, document_id))")
        cur.execute("SELECT to_regclass('user_scenarios') IS NULL")
        if cur.fetchone()[0]:
            main._ensure_user_scenarios_table()
        cur.execute("SELECT to_regclass('scenario_settings') IS NULL")
        if cur.fetchone()[0]:
            main._ensure_scenario_settings_table()
        cur.execute("DELETE FROM user_scenarios WHERE id = %s", (SID,))
        cur.execute("DELETE FROM scenario_settings WHERE scenario_id = %s", (SID,))
        cur.execute(
            "INSERT INTO user_scenarios (id, name, query, mode, filters) "
            "VALUES (%s, 'Rerank', 'hpai', 'boolean', '{}')", (SID,))
        cur.execute(
            "INSERT INTO literature_document (id, title, abstract) VALUES "
            "(1, 'On topic, reranked high', 'abstract one long enough'),"
            "(2, 'Off topic, similar but reranked low', 'abstract two long enough'),"
            "(3, 'Never reranked yet', 'abstract three long enough'),"
            "(4, 'Below the similarity threshold', 'abstract four long enough'),"
            "(5, 'Reranked low but included by hand', 'abstract five long enough')")
        # 2 a une similarité PLUS HAUTE que 1 : c'est la situation réelle du corpus HPAI.
        cur.execute(
            "INSERT INTO article_scenarios (scenario_id, document_id, similarity_score,"
            " rerank_score, screening_status) VALUES "
            "(%s, 1, 0.36, 0.59, NULL),"
            "(%s, 2, 0.40, 0.07, NULL),"
            "(%s, 3, 0.38, NULL, NULL),"
            "(%s, 4, 0.10, 0.90, NULL),"
            "(%s, 5, 0.40, 0.02, 'included')", (SID, SID, SID, SID, SID))
    yield db_conn
    with db_conn.cursor() as cur:
        cur.execute("DELETE FROM user_scenarios WHERE id = %s", (SID,))
        cur.execute("DELETE FROM scenario_settings WHERE scenario_id = %s", (SID,))


def _relevant(thr: float = 0.3) -> set[int]:
    from sqlalchemy import text
    sql = (f"SELECT d.id FROM literature_document d"
           f" JOIN article_scenarios ars ON ars.document_id = d.id"
           f" WHERE ars.scenario_id = :sid AND {relevant_gate_sql()}")
    with main.engine.connect() as conn:
        return {r[0] for r in conn.execute(text(sql), {"sid": SID, "thr": thr})}


def _set_rerank_threshold(value) -> None:
    from sqlalchemy import text
    with main.engine.begin() as conn:
        conn.execute(text(
            "INSERT INTO scenario_settings (scenario_id, rerank_threshold)"
            " VALUES (:sid, :v) ON CONFLICT (scenario_id)"
            " DO UPDATE SET rerank_threshold = :v"), {"sid": SID, "v": value})


def test_with_no_setting_at_all_the_gate_is_exactly_the_old_one(seeded):
    """Aucune ligne de réglages : la colonne ne peut pas filtrer."""
    assert _relevant() == {1, 2, 3, 5}          # 4 est sous le seuil de similarité


def test_a_zero_threshold_changes_nothing(seeded):
    _set_rerank_threshold(0)
    assert _relevant() == {1, 2, 3, 5}


def test_a_null_threshold_changes_nothing(seeded):
    """La colonne existe mais n'a jamais été réglée : NULL vaut 0, pas « tout exclure »."""
    _set_rerank_threshold(None)
    assert _relevant() == {1, 2, 3, 5}


def test_the_rerank_cut_drops_the_off_topic_article_the_similarity_cut_could_not(seeded):
    """Le coeur de la fonctionnalité.

    L'article 2 a une similarité PLUS HAUTE que l'article 1. Aucun seuil de similarité ne
    peut retirer 2 en gardant 1. Le rerank le fait."""
    _set_rerank_threshold(0.26)
    kept = _relevant()
    assert 1 in kept, "l'article du sujet a été jeté"
    assert 2 not in kept, "l'article hors sujet a survécu"


def test_no_similarity_threshold_can_do_the_same(seeded):
    """La démonstration par l'absurde, pour que personne ne retire ce code en croyant
    qu'un curseur suffisait."""
    for thr in (0.30, 0.35, 0.37, 0.39, 0.401):
        kept = _relevant(thr)
        assert not (1 in kept and 2 not in kept), (
            f"à {thr}, la similarité aurait séparé les deux : le test ne prouve plus rien")


def test_an_article_not_yet_reranked_survives_any_cut(seeded):
    """45 des 602 pertinents du corpus HPAI étaient dans ce cas."""
    for thr in (0.1, 0.5, 0.95, 1.0):
        _set_rerank_threshold(thr)
        assert 3 in _relevant(), f"l'article non reranké a disparu au seuil {thr}"


def test_a_hand_included_article_survives_the_rerank_cut(seeded):
    """Le rerank ne peut pas défaire la décision d'un relecteur."""
    _set_rerank_threshold(0.95)
    assert 5 in _relevant()


def test_the_rerank_cut_does_not_rescue_an_article_below_the_similarity_cut(seeded):
    """Les deux seuils se cumulent, ils ne se remplacent pas : l'article 4 a le meilleur
    rerank du lot et reste dehors, parce que sa similarité est sous le seuil."""
    _set_rerank_threshold(0.5)
    assert 4 not in _relevant()


def test_the_two_counters_agree_with_the_gate(seeded):
    """Le compteur du corpus passe par la même porte : il doit bouger avec elle."""
    from sqlalchemy import text
    _set_rerank_threshold(0.26)
    with main.engine.connect() as conn:
        row = conn.execute(text(main.scenario_counts_sql()),
                           {"sid": SID, "thr": 0.3}).mappings().first()
    assert int(row["relevant"]) == len(_relevant())


# ─── Le réglage, par l'API ───────────────────────────────────────────────────

def test_a_threshold_outside_zero_one_is_refused(seeded):
    from fastapi import HTTPException
    for bad in (45, -0.1, 1.5):
        with pytest.raises(HTTPException) as e:
            main.update_scenario_settings(SID, {"rerank_threshold": bad}, None)
        assert e.value.status_code == 422
    with pytest.raises(HTTPException):
        main.update_scenario_settings(SID, {"rerank_threshold": "beaucoup"}, None)


def test_the_setting_round_trips(seeded):
    out = main.update_scenario_settings(SID, {"rerank_threshold": 0.26}, None)
    assert out["rerank_threshold"] == pytest.approx(0.26)
    assert main.get_scenario_settings(SID)["rerank_threshold"] == pytest.approx(0.26)


def test_an_unset_scenario_reads_as_zero_not_as_null(seeded):
    """L'interface affiche ce nombre sur un curseur : None l'aurait laissé vide."""
    assert main.get_scenario_settings(SID)["rerank_threshold"] == DEFAULT_RERANK_THRESHOLD


def test_moving_the_rerank_threshold_invalidates_the_derived_caches(seeded):
    """Le clustering et les actions recommandées sont des fonctions du corpus, et le
    rerank découpe le corpus autant que la similarité."""
    from sqlalchemy import text
    with main.engine.begin() as conn:
        conn.execute(text(
            "INSERT INTO scenario_settings (scenario_id, clustering_json)"
            " VALUES (:sid, '{\"stale\": true}'::jsonb) ON CONFLICT (scenario_id)"
            " DO UPDATE SET clustering_json = '{\"stale\": true}'::jsonb"), {"sid": SID})
    main.update_scenario_settings(SID, {"rerank_threshold": 0.4}, None)
    with main.engine.connect() as conn:
        left = conn.execute(text(
            "SELECT clustering_json FROM scenario_settings WHERE scenario_id = :sid"),
            {"sid": SID}).scalar()
    assert left is None, "le clustering d'avant la coupe était encore servi"


# ─── La courbe ───────────────────────────────────────────────────────────────

def test_the_curve_refuses_a_score_it_does_not_know(seeded):
    from fastapi import HTTPException
    with pytest.raises(HTTPException) as e:
        main.get_threshold_curve(SID, None, "vibes")
    assert e.value.status_code == 422


def test_the_similarity_curve_is_unchanged(seeded):
    out = main.get_threshold_curve(SID, None, "similarity")
    assert out["score"] == "similarity"
    assert out["unscored_are_kept"] is False
    assert out["always_kept"] == out["included"]


def test_the_rerank_curve_counts_the_unreranked_among_those_kept_for_free(seeded):
    """Un article non reranké passe quel que soit le seuil, donc il appartient au compte
    de ce qui passe d'office, pas à l'axe des seuils."""
    out = main.get_threshold_curve(SID, None, "rerank")
    assert out["score"] == "rerank"
    assert out["unscored_are_kept"] is True
    assert out["unscored"] == 1                        # l'article 3
    assert out["always_kept"] == out["included"] + 1   # l'inclus à la main, plus lui
    assert all(p["kept"] >= out["always_kept"] for p in out["curve"])
