"""GET /gesica/scenarios must stay cheap no matter how large the corpora grow.

Production, 2026-09-10: nginx answered 502 on /api/gesica/scenarios ("Failed to load
scenarios") and, when it did answer, the list took minutes. The route loaded EVERY
article of EVERY scenario — user scenarios included, which it does not even list — with
their abstracts, in ONE query, then serialised all of it. A single user scenario whose
lexical search had matched 238 000 documents was enough. The frontend never displays
that list (App.tsx: `false && scenario.relevantArticles…`); a scenario's articles are
read, paginated, from /gesica/scenarios/{id}/corpus.

This seeds one system scenario with a few articles and one user scenario with many more,
and checks that the list answers with the right counts and NO article payload. It owns
the three corpus tables the way the other integration tests do, and skips cleanly when
no Postgres is reachable.
"""
import pytest

pytest.importorskip("fastapi")
pytest.importorskip("httpx")

import main  # noqa: E402

SYS_ID = "sys-list-payload"
USR_ID = "usr-list-payload"
USER_DOCS = 300          # enough that leaking them would show in the response size
MARKER = "USRDOC-ABSTRACT-MUST-NOT-BE-IN-THE-LIST"


def _engine_ok() -> bool:
    try:
        with main.engine.connect():
            return True
    except Exception:
        return False


@pytest.fixture()
def seeded(db_conn):
    if not _engine_ok():
        pytest.skip("main.engine cannot reach the database")
    with db_conn.cursor() as cur:
        cur.execute("DROP TABLE IF EXISTS document_chunk, article_scenarios, literature_document CASCADE")
        cur.execute(
            "CREATE TABLE literature_document ("
            "id bigint PRIMARY KEY, title text NOT NULL, source text NOT NULL, abstract text,"
            "year int, is_duplicate boolean DEFAULT false, screening_status text,"
            "project_context text DEFAULT 'literev')"
        )
        cur.execute(
            "CREATE TABLE document_chunk ("
            "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "document_id bigint NOT NULL REFERENCES literature_document(id) ON DELETE CASCADE,"
            "chunk_index int DEFAULT 0, content text, chunk_type text)"
        )
        cur.execute(
            "CREATE TABLE article_scenarios ("
            "scenario_id text, document_id bigint, similarity_score double precision,"
            "screening_status text, PRIMARY KEY (scenario_id, document_id))"
        )
        # The scenario tables come from the app's own boot DDL (run at import); only the
        # rows are ours. Recreate them if an earlier test left the database without them.
        cur.execute("SELECT to_regclass('user_scenarios') IS NULL")
        if cur.fetchone()[0]:
            main._ensure_user_scenarios_table()
        cur.execute("INSERT INTO user_scenario_folders (id, name) VALUES (%s, %s) "
                    "ON CONFLICT (id) DO NOTHING", (main.GESICA_FOLDER_ID, "GESICA"))
        cur.execute("DELETE FROM user_scenarios WHERE id IN (%s, %s)", (SYS_ID, USR_ID))
        cur.execute(
            "INSERT INTO user_scenarios (id, name, query, mode, filters, is_system, folder_id, hidden) "
            "VALUES (%s, %s, %s, 'boolean', '{}', TRUE, %s, FALSE)",
            (SYS_ID, "System scenario", "influenza AND forecasting", main.GESICA_FOLDER_ID))
        cur.execute(
            "INSERT INTO user_scenarios (id, name, query, mode, filters, is_system, folder_id) "
            "VALUES (%s, %s, %s, 'boolean', '{}', FALSE, NULL)",
            (USR_ID, "User scenario", "AI OR ML AND infection"))
        # system scenario: 3 articles, one of them a duplicate → counts 2
        cur.execute(
            "INSERT INTO literature_document (id, title, source, abstract, year, is_duplicate, screening_status) VALUES "
            "(1, 'Sys doc one', 'pubmed', 'abstract one', 2021, false, 'included'),"
            "(2, 'Sys doc two', 'pubmed', 'abstract two', 2022, false, NULL),"
            "(3, 'Sys doc dup', 'pubmed', 'abstract dup', 2022, true, NULL)")
        cur.execute("INSERT INTO article_scenarios (scenario_id, document_id) VALUES "
                    "(%s, 1), (%s, 2), (%s, 3)", (SYS_ID, SYS_ID, SYS_ID))
        # user scenario: many articles with long abstracts — the payload that used to leak
        cur.executemany(
            "INSERT INTO literature_document (id, title, source, abstract, year) VALUES (%s, %s, 'pubmed', %s, 2020)",
            [(100 + i, f"User doc {i}", MARKER * 10) for i in range(USER_DOCS)])
        cur.executemany("INSERT INTO article_scenarios (scenario_id, document_id) VALUES (%s, %s)",
                        [(USR_ID, 100 + i) for i in range(USER_DOCS)])
    yield db_conn
    with db_conn.cursor() as cur:
        cur.execute("DELETE FROM user_scenarios WHERE id IN (%s, %s)", (SYS_ID, USR_ID))


def test_the_list_carries_counts_but_no_articles(seeded):
    from fastapi.testclient import TestClient
    r = TestClient(main.app).get("/gesica/scenarios")
    assert r.status_code == 200, r.text
    rows = {s["id"]: s for s in r.json()}
    assert SYS_ID in rows
    assert USR_ID not in rows                      # user scenarios are not listed here…
    assert MARKER not in r.text                    # …and their articles must not travel either
    sys_row = rows[SYS_ID]
    assert sys_row["article_count"] == 2           # the duplicate is not counted
    assert sys_row["included_count"] == 1
    assert sys_row["excluded_count"] == 0
    assert sys_row["relevant_articles"] == []      # the field stays, empty, for the client type
    # the response must not scale with the corpora: 300 abstracts would be ~120 kB alone
    assert len(r.content) < 20_000, len(r.content)
