"""Le rerank ne notait qu'une partie du corpus, et rien ne le disait.

Mesuré sur l'installation : 22 562 des 35 363 lignes pertinentes n'avaient aucun score
de rerank, soit 63,8 %, et 5 scénarios sur 31 seulement étaient complets. Trois causes,
chacune épinglée ici :

1. UN PLAFOND DE 1000 en dur dans la signature, qu'aucun appelant ne surchargeait.
   10 480 lignes de 7 scénarios tombaient au-delà du millième rang.
2. LA SÉLECTION LISAIT LE SEUIL au moment du lancement, donc tout ce qui passait sous le
   curseur n'était jamais envoyé. La preuve était une partition parfaite : sur HPAI, plus
   bas score noté 0.303309, plus haut non noté 0.299115, rien entre les deux. Une
   variable continue ne se partitionne pas toute seule. Et c'est précisément l'article
   sous le seuil dont on a besoin du score pour décider de le faire entrer.
3. UN SEUL APPEL pour tout le lot : un scénario de 3 424 candidats les envoyait ensemble,
   et la moindre erreur rendait 0, perdant le travail entier.

Le quatrième défaut n'est pas dans la fonction mais autour : le cross-encoder était
INATTEIGNABLE depuis le chemin automatique normal, parce que son appel était gardé par
`if _pipeline_callback is None` alors que le pipeline complet passe un callback. Huit
scénarios n'avaient aucun score pour cette seule raison.
"""
import os

import pytest

pytest.importorskip("fastapi")

import main  # noqa: E402
from api import relevance as R  # noqa: E402

SID = "rerank-cov"


def _engine_ok() -> bool:
    try:
        with main.engine.connect():
            return True
    except Exception:
        return False


# ─── Ce qui se lit sans base ─────────────────────────────────────────────────

def test_there_is_no_default_cap_any_more():
    assert R.RERANK_MAX_ARTICLES == 0, "un plafond par défaut est revenu"


def test_a_cap_is_still_available_as_an_operational_fallback():
    assert "RERANK_MAX_ARTICLES" in R.__dict__
    from api.core import _env_int
    assert _env_int("RERANK_MAX_ARTICLES", 0, 0) == 0


def test_the_batch_size_is_small_enough_for_one_request():
    assert 1 <= R._RERANK_BATCH <= 1000


def test_the_pipeline_no_longer_hides_the_cross_encoder_behind_the_callback_guard():
    """La cause des 8 scénarios à zéro : le garde était vrai seulement sur /populate."""
    src = open("api/pipeline.py", encoding="utf-8").read()
    i = src.index("_post_done_bg")
    before = src[max(0, i - 1200):i]
    assert "if _pipeline_callback is None:" not in before, (
        "le garde qui rendait le cross-encoder inatteignable est revenu")


# ─── Contre une vraie base, avec un Cohere simulé ────────────────────────────

@pytest.fixture()
def seeded(db_conn, monkeypatch):
    if not _engine_ok():
        pytest.skip("main.engine cannot reach the database")
    monkeypatch.setenv("COHERE_API_KEY", "test-key")
    with db_conn.cursor() as cur:
        cur.execute("DROP TABLE IF EXISTS document_search")
        cur.execute("DROP TABLE IF EXISTS document_chunk, article_scenarios, literature_document CASCADE")
        cur.execute(
            "CREATE TABLE literature_document ("
            "id bigint PRIMARY KEY, title text NOT NULL, source text NOT NULL DEFAULT 'pubmed',"
            "abstract text, year int, is_duplicate boolean DEFAULT false, screening_status text,"
            "journal text, doi text, authors text, keywords text, citation_count int,"
            "quality_score double precision, metadata_json jsonb, has_fulltext boolean,"
            "pico_json jsonb, study_design text, created_at timestamptz DEFAULT now(),"
            "project_context text DEFAULT 'literev')")
        cur.execute(
            "CREATE TABLE document_chunk ("
            "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "document_id bigint NOT NULL REFERENCES literature_document(id) ON DELETE CASCADE,"
            "chunk_index int DEFAULT 0, content text, chunk_type text, embedding text)")
        cur.execute(
            "CREATE TABLE article_scenarios (scenario_id text, document_id bigint,"
            "similarity_score double precision, rerank_score double precision,"
            "screening_status text, reviewer_1_status text, reviewer_2_status text,"
            "PRIMARY KEY (scenario_id, document_id))")
        cur.execute("SELECT to_regclass('user_scenarios') IS NULL")
        if cur.fetchone()[0]:
            main._ensure_user_scenarios_table()
        cur.execute("SELECT to_regclass('scenario_settings') IS NULL")
        if cur.fetchone()[0]:
            main._ensure_scenario_settings_table()
        cur.execute("DELETE FROM user_scenarios WHERE id = %s", (SID,))
        cur.execute("DELETE FROM scenario_settings WHERE scenario_id = %s", (SID,))
        cur.execute(
            "INSERT INTO user_scenarios (id, name, query, mode, filters) "
            "VALUES (%s, 'Cov', 'hpai', 'boolean', '{}')", (SID,))
        # Un seuil haut : sous l'ancien code, rien sous 0.80 n'était jamais envoyé.
        cur.execute(
            "INSERT INTO scenario_settings (scenario_id, similarity_threshold) VALUES (%s, 0.80)",
            (SID,))
        rows = []
        for i in range(1, 26):
            sim = 0.95 - (i - 1) * 0.03          # de 0.95 à 0.23 : la plupart sous 0.80
            rows.append((i, f"Article {i}", "abstract long enough to be scorable " * 3, sim))
        cur.executemany(
            "INSERT INTO literature_document (id, title, abstract) VALUES (%s, %s, %s)",
            [(r[0], r[1], r[2]) for r in rows])
        cur.executemany(
            "INSERT INTO article_scenarios (scenario_id, document_id, similarity_score)"
            " VALUES (%s, %s, %s)", [(SID, r[0], r[3]) for r in rows])
        # Un article sans résumé utilisable : il ne peut PAS être noté, jamais.
        cur.execute("INSERT INTO literature_document (id, title, abstract) VALUES (99, 'No abstract', 'tiny')")
        cur.execute("INSERT INTO article_scenarios (scenario_id, document_id, similarity_score)"
                    " VALUES (%s, 99, 0.90)", (SID,))
        # Un doublon : hors corpus par la porte, donc hors du rerank aussi.
        cur.execute("INSERT INTO literature_document (id, title, abstract, is_duplicate)"
                    " VALUES (98, 'Dup', 'abstract long enough to be scorable here', true)")
        cur.execute("INSERT INTO article_scenarios (scenario_id, document_id, similarity_score)"
                    " VALUES (%s, 98, 0.90)", (SID,))
    yield db_conn
    with db_conn.cursor() as cur:
        cur.execute("DELETE FROM user_scenarios WHERE id = %s", (SID,))
        cur.execute("DELETE FROM scenario_settings WHERE scenario_id = %s", (SID,))


def _fake_cohere(calls):
    def _f(query, docs, model="rerank-v3.5"):
        calls.append(len(docs))
        return [0.5] * len(docs)
    return _f


def _scored(db_conn) -> int:
    with db_conn.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM article_scenarios"
                    " WHERE scenario_id = %s AND rerank_score IS NOT NULL", (SID,))
        return cur.fetchone()[0]


def test_every_scorable_article_is_scored_whatever_the_threshold(seeded, db_conn, monkeypatch):
    """Le coeur : 25 articles, seuil à 0.80, et les 25 sont notés."""
    monkeypatch.setattr(R, "_cohere_rerank", _fake_cohere([]))
    out = R._run_cross_encoder_rerank(SID, "hpai")
    assert out["candidates"] == 25, "la sélection suit encore le seuil"
    assert out["scored"] == 25
    assert _scored(db_conn) == 25


def test_an_article_below_the_threshold_gets_a_score(seeded, db_conn, monkeypatch):
    """Sans quoi on ne peut jamais décider de le faire entrer : c'est le score qui
    manque précisément là où la décision se prend."""
    monkeypatch.setattr(R, "_cohere_rerank", _fake_cohere([]))
    R._run_cross_encoder_rerank(SID, "hpai")
    with db_conn.cursor() as cur:
        cur.execute("SELECT rerank_score FROM article_scenarios"
                    " WHERE scenario_id = %s AND document_id = 25", (SID,))   # sim ~0.23
        assert cur.fetchone()[0] is not None


def test_the_call_is_batched(seeded, monkeypatch):
    calls: list[int] = []
    monkeypatch.setattr(R, "_cohere_rerank", _fake_cohere(calls))
    monkeypatch.setattr(R, "_RERANK_BATCH", 10)
    R._run_cross_encoder_rerank(SID, "hpai")
    assert calls == [10, 10, 5], f"un seul envoi, ou un découpage inattendu : {calls}"


def test_a_failing_batch_does_not_lose_the_others(seeded, db_conn, monkeypatch):
    """Avant : une erreur rendait 0 et rien n'était écrit, pour tout le corpus."""
    seen = {"n": 0}

    def _flaky(query, docs, model="rerank-v3.5"):
        seen["n"] += 1
        if seen["n"] == 2:
            return None                    # le deuxième lot échoue
        return [0.5] * len(docs)

    monkeypatch.setattr(R, "_cohere_rerank", _flaky)
    monkeypatch.setattr(R, "_RERANK_BATCH", 10)
    out = R._run_cross_encoder_rerank(SID, "hpai")
    assert out["batches_failed"] == 1
    assert out["batches_ok"] == 2
    assert _scored(db_conn) == 15          # 10 + 5, le lot du milieu manque
    assert out["scored"] == 15


def test_only_missing_does_not_pay_twice(seeded, db_conn, monkeypatch):
    calls: list[int] = []
    monkeypatch.setattr(R, "_cohere_rerank", _fake_cohere(calls))
    R._run_cross_encoder_rerank(SID, "hpai")
    calls.clear()
    with db_conn.cursor() as cur:
        cur.execute("UPDATE article_scenarios SET rerank_score = NULL"
                    " WHERE scenario_id = %s AND document_id IN (3, 7)", (SID,))
    out = R._run_cross_encoder_rerank(SID, "hpai", only_missing=True)
    assert out["candidates"] == 2 and out["scored"] == 2
    assert calls == [2], "le rattrapage a renvoyé des articles déjà notés"


def test_an_article_without_a_usable_abstract_is_never_a_candidate(seeded, monkeypatch):
    monkeypatch.setattr(R, "_cohere_rerank", _fake_cohere([]))
    out = R._run_cross_encoder_rerank(SID, "hpai")
    assert out["candidates"] == 25          # ni le 99 sans résumé, ni le 98 doublon


def test_a_cap_still_works_when_someone_sets_one(seeded, monkeypatch):
    monkeypatch.setattr(R, "_cohere_rerank", _fake_cohere([]))
    out = R._run_cross_encoder_rerank(SID, "hpai", top_k=5)
    assert out["candidates"] == 5


def test_no_key_says_so_rather_than_looking_like_success(seeded, monkeypatch):
    monkeypatch.delenv("COHERE_API_KEY", raising=False)
    out = R._run_cross_encoder_rerank(SID, "hpai")
    assert out["skipped_no_key"] == 1 and out["scored"] == 0


# ─── Ce que le statut raconte ────────────────────────────────────────────────

def test_the_status_reports_real_coverage_not_just_the_in_memory_job(seeded, monkeypatch):
    """« idle » voulait dire « je ne me souviens de rien », pas « à jour » : le job vit en
    mémoire et chaque déploiement le vide."""
    st = main.get_rerank_status(SID)
    assert st["scorable"] == 25
    assert st["missing"] == 25
    assert st["unscorable"] == 1            # l'article sans résumé, dit plutôt que caché
    monkeypatch.setattr(R, "_cohere_rerank", _fake_cohere([]))
    R._run_cross_encoder_rerank(SID, "hpai")
    st2 = main.get_rerank_status(SID)
    assert st2["missing"] == 0 and st2["scorable"] == 25
