"""Two figures in the synthesis payload described something other than they claimed.

Neither was rendered, so no screen lied; but the payload is an interface, and both
were read by anyone calling the route rather than using the page.

- `double_blind_stats` was a literal block of zeros, so a scenario screened by two
  reviewers reported that neither had done anything. The columns had been there all
  along.
- `pico_coverage_pct` divided by the WHOLE corpus while every other number beside it
  counts the relevant subset, so it fell with every article below the threshold and
  disagreed with the percentage the screen computes for itself.
"""
import pytest

pytest.importorskip("fastapi")

import main  # noqa: E402

SID = "payload-truth"


def _engine_ok() -> bool:
    try:
        with main.engine.connect():
            return True
    except Exception:
        return False


@pytest.fixture()
def seeded(db_conn):
    if not _engine_ok():
        pytest.skip("main.engine cannot reach the database")
    with db_conn.cursor() as cur:
        cur.execute("DROP TABLE IF EXISTS document_search")
        cur.execute("DROP TABLE IF EXISTS document_chunk, article_scenarios, literature_document CASCADE")
        cur.execute(
            "CREATE TABLE literature_document ("
            "id bigint PRIMARY KEY, title text NOT NULL, source text NOT NULL DEFAULT 'pubmed',"
            "abstract text, year int, is_duplicate boolean DEFAULT false, screening_status text,"
            "journal text, doi text, authors text, keywords text, citation_count int,"
            "quality_score double precision, metadata_json jsonb, has_fulltext boolean,"
            "pico_json jsonb, study_design text, created_at timestamptz DEFAULT now(),"
            "project_context text DEFAULT 'literev')")
        cur.execute(
            "CREATE TABLE document_chunk ("
            "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "document_id bigint NOT NULL REFERENCES literature_document(id) ON DELETE CASCADE,"
            "chunk_index int DEFAULT 0, content text, chunk_type text, embedding text)")
        cur.execute(
            "CREATE TABLE article_scenarios (scenario_id text, document_id bigint,"
            "similarity_score double precision, rerank_score double precision,"
            "screening_status text, reviewer_1_status text, reviewer_2_status text,"
            "PRIMARY KEY (scenario_id, document_id))")
        cur.execute("SELECT to_regclass('user_scenarios') IS NULL")
        if cur.fetchone()[0]:
            main._ensure_user_scenarios_table()
        cur.execute("DELETE FROM user_scenarios WHERE id = %s", (SID,))
        cur.execute(
            "INSERT INTO user_scenarios (id, name, query, mode, filters) "
            "VALUES (%s, 'Truth', 'rsv', 'boolean', '{}')", (SID,))
        # 1 et 2 pertinents et avec PICO, 3 pertinent sans PICO, 4 et 5 sous le seuil.
        cur.execute(
            "INSERT INTO literature_document (id, title, abstract, pico_json) VALUES "
            "(1, 'A', 'abstract one long enough', '{\"P\": \"x\"}'),"
            "(2, 'B', 'abstract two long enough', '{\"P\": \"y\"}'),"
            "(3, 'C', 'abstract three long enough', NULL),"
            "(4, 'D', 'abstract four long enough', NULL),"
            "(5, 'E', 'abstract five long enough', NULL)")
        cur.execute(
            "INSERT INTO article_scenarios (scenario_id, document_id, similarity_score,"
            " reviewer_1_status, reviewer_2_status) VALUES "
            "(%s, 1, 0.90, 'included', 'included'),"      # les deux, d'accord
            "(%s, 2, 0.80, 'included', 'excluded'),"      # les deux, en conflit
            "(%s, 3, 0.70, 'included', NULL),"            # un seul
            "(%s, 4, 0.10, NULL, NULL),"
            "(%s, 5, 0.05, NULL, NULL)", (SID, SID, SID, SID, SID))
    yield db_conn
    with db_conn.cursor() as cur:
        cur.execute("DELETE FROM user_scenarios WHERE id = %s", (SID,))


def test_the_double_blind_block_counts_what_the_reviewers_really_did(seeded):
    st = main.get_evidence_brief(SID)["double_blind_stats"]
    assert st["reviewer_1_done"] == 3
    assert st["reviewer_2_done"] == 2
    assert st["both_done"] == 2
    assert st["agreements"] == 1
    assert st["conflicts"] == 1


def test_a_scenario_nobody_screened_twice_still_reads_as_zero(seeded, db_conn):
    """Zero must mean zero, which is exactly what the literal block could not say."""
    with db_conn.cursor() as cur:
        cur.execute("UPDATE article_scenarios SET reviewer_1_status = NULL,"
                    " reviewer_2_status = NULL WHERE scenario_id = %s", (SID,))
    st = main.get_evidence_brief(SID)["double_blind_stats"]
    assert set(st.values()) == {0}


def test_pico_coverage_is_counted_over_the_relevant_subset(seeded):
    """Three articles are relevant and two carry a PICO: two thirds, not two fifths."""
    cs = main.get_evidence_brief(SID)["corpus_stats"]
    assert cs["relevant"] == 3 and cs["relevant_with_pico"] == 2
    assert cs["pico_coverage_pct"] == 66.7            # et non 40.0 sur les cinq
