"""Integration test for the corpus-maintenance admin endpoint.

Seeds duplicates + legacy/junk/substantive chunks + article_scenarios via raw
psycopg, then drives `main.corpus_maintenance` (which uses `main.engine`) through
dry-run → apply → idempotent re-run, asserting counts, chunk CASCADE, the
explicit article_scenarios delete (that table has no FK), the 'full_text' retype,
junk deletion, and that restore-point backup tables are created.

Skips when no Postgres is reachable (see conftest.db_conn) or when this
SQLAlchemy/psycopg build can't probe the server version — a known sandbox-only
quirk (`_get_server_version_info` gets bytes); CI and production are unaffected.
"""
import pytest

import main

LONG = "this is a long substantive chunk body well over twenty characters"


def _engine_ok() -> bool:
    try:
        with main.engine.connect():
            return True
    except Exception:
        return False


def _seed(conn):
    with conn.cursor() as cur:
        cur.execute("DROP TABLE IF EXISTS document_chunk, article_scenarios, literature_document CASCADE")
        cur.execute(
            "CREATE TABLE literature_document ("
            "id bigint PRIMARY KEY, title text NOT NULL, source text NOT NULL, abstract text,"
            "is_duplicate boolean DEFAULT false, project_context text DEFAULT 'literev')"
        )
        cur.execute(
            "CREATE TABLE document_chunk ("
            "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "document_id bigint NOT NULL REFERENCES literature_document(id) ON DELETE CASCADE,"
            "chunk_index int DEFAULT 0, content text, chunk_type text, embedding text)"
        )
        cur.execute(
            "CREATE TABLE article_scenarios ("  # deliberately NO FK, mirroring production
            "scenario_id text, document_id bigint, similarity_score double precision,"
            "PRIMARY KEY (scenario_id, document_id))"
        )
        cur.execute(
            "INSERT INTO literature_document (id,title,source,abstract,is_duplicate) VALUES "
            "(1,'D1','pubmed','a',false),(2,'D2','pmc','b',false),"
            "(3,'D3','pubmed','c',true),(4,'D4','pmc','d',true)"
        )
        rows = [
            (1, "ta1", "title_abstract", "[0.1]"),
            (1, LONG, "fulltext_section", "[0.1]"),
            (1, LONG + " 2", "fulltext_section", "[0.1]"),
            (2, "ta2", "title_abstract", "[0.1]"),
            (3, "ta3", "title_abstract", "[0.1]"),      # on duplicate -> cascade
            (3, LONG, "fulltext_section", "[0.1]"),     # on duplicate -> cascade
            (4, "ta4", "title_abstract", None),         # on duplicate -> cascade
            (1, LONG, "full_text", "[0.1]"),            # legacy -> retype
            (2, "x", None, None),                       # junk (null type, short)
            (1, " ", "weird_type", None),               # junk (short)
            (2, LONG, "live_api_persisted", None),      # substantive -> kept/reported
        ]
        for did, content, ct, emb in rows:
            cur.execute(
                "INSERT INTO document_chunk (document_id,content,chunk_type,embedding) VALUES (%s,%s,%s,%s)",
                (did, content, ct, emb),
            )
        cur.execute(
            "INSERT INTO article_scenarios VALUES ('sc-a',1,0.9),('sc-a',3,0.8),('sc-b',4,0.7)"
        )


def _count(conn, sql: str) -> int:
    with conn.cursor() as cur:
        cur.execute(sql)
        return cur.fetchone()[0]


def test_corpus_maintenance_end_to_end(db_conn):
    if not _engine_ok():
        pytest.skip("main.engine cannot connect here (SQLAlchemy/psycopg version-probe quirk)")
    _seed(db_conn)

    # ── DRY RUN: reports, writes nothing ────────────────────────────────────
    r = main.corpus_maintenance(main.CorpusMaintenanceIn(dry_run=True), None)
    assert r["dry_run"] is True
    assert r["duplicates"]["documents"] == 2
    assert r["duplicates"]["chunks_cascade"] == 3
    assert r["duplicates"]["article_scenarios"] == 2
    assert r["legacy_chunks"]["legacy_full_text_to_retype"] == 1
    assert r["legacy_chunks"]["junk_to_delete"] == 2
    assert r["legacy_chunks"]["substantive_kept_reported"] == 1
    assert _count(db_conn, "SELECT count(*) FROM literature_document") == 4  # untouched
    assert r["backups"] == []

    # ── APPLY ───────────────────────────────────────────────────────────────
    r2 = main.corpus_maintenance(main.CorpusMaintenanceIn(dry_run=False), None)
    assert r2["duplicates"]["deleted_documents"] == 2
    assert r2["legacy_chunks"]["retyped"] == 1
    assert r2["legacy_chunks"]["deleted_junk"] == 2
    assert len(r2["backups"]) == 4  # docs, chunks, ars, junkchunks
    assert _count(db_conn, "SELECT count(*) FROM literature_document") == 2
    # doc1: {title_abstract, 2x fulltext_section, full_text->fulltext_section} = 4
    # doc2: {title_abstract, live_api_persisted} = 2  (null junk deleted)
    assert _count(db_conn, "SELECT count(*) FROM document_chunk") == 6
    assert _count(db_conn, "SELECT count(*) FROM document_chunk WHERE chunk_type='full_text'") == 0
    assert _count(db_conn, "SELECT count(*) FROM document_chunk WHERE chunk_type='fulltext_section'") == 3
    assert _count(db_conn, "SELECT count(*) FROM article_scenarios") == 1  # only sc-a/doc1

    # ── IDEMPOTENT re-run ───────────────────────────────────────────────────
    r3 = main.corpus_maintenance(main.CorpusMaintenanceIn(dry_run=False), None)
    assert r3["duplicates"]["documents"] == 0
    assert r3["legacy_chunks"]["legacy_full_text_to_retype"] == 0
    assert r3["legacy_chunks"]["junk_to_delete"] == 0
    assert r3["legacy_chunks"]["substantive_kept_reported"] == 1  # still reported, still kept
