"""Every article count the interface shows for a scenario must agree once a pipeline ends.

Observed on 14 Sep: the scenario card said 22,707 articles, the scenario header 25,140,
the PRISMA box 25,140 — while the full pipeline was still running. Not a bug in any one
number: the card reads a stored copy updated in stages during a search (local matches
first, cleaned corpus later), PRISMA reads figures frozen at the end of the search, the
semantic stage reads the database live. The fix is to say so while a pipeline runs, to
refresh everything at the end, and to CHECK that the numbers agree — which is what
`_counts_consistency` / `_scenario_counts` / GET /user-scenarios/{id}/counts do.
"""
import pytest

pytest.importorskip("fastapi")
pytest.importorskip("httpx")

import main  # noqa: E402


# ── the comparison (pure) ────────────────────────────────────────────────────

def test_agreeing_counts_are_consistent():
    ok, mismatches = main._counts_consistency(
        {"article_count": 25140, "corpus_links": 25140, "prisma_screened": 25140,
         "above_threshold": 3625, "below_threshold": 21515, "embedded": 25140})
    assert ok is True and mismatches == []


def test_each_divergent_reading_is_named_with_the_expected_value():
    ok, mismatches = main._counts_consistency(
        {"article_count": 22707, "corpus_links": 25140, "prisma_screened": 25000,
         "above_threshold": 3625, "below_threshold": 21514})
    assert ok is False
    assert {m["field"] for m in mismatches} == {"article_count", "prisma_screened", "above_plus_below"}
    by_field = {m["field"]: m for m in mismatches}
    assert by_field["article_count"] == {"field": "article_count", "value": 22707, "expected": 25140}
    assert by_field["above_plus_below"]["value"] == 25139


def test_a_scenario_never_searched_has_no_prisma_figure_to_compare():
    """Before the first run there is nothing stored: None is "not applicable", not 0."""
    ok, mismatches = main._counts_consistency(
        {"article_count": 0, "corpus_links": 0, "prisma_screened": None,
         "above_threshold": 0, "below_threshold": 0})
    assert ok is True and mismatches == []


# ── the endpoint (database) ──────────────────────────────────────────────────

SID = "counts-check"


def _engine_ok() -> bool:
    try:
        with main.engine.connect():
            return True
    except Exception:
        return False


@pytest.fixture()
def seeded(db_conn):
    if not _engine_ok():
        pytest.skip("main.engine cannot reach the database")
    with db_conn.cursor() as cur:
        cur.execute("DROP TABLE IF EXISTS document_search")
        cur.execute("DROP TABLE IF EXISTS document_chunk, article_scenarios, literature_document CASCADE")
        cur.execute(
            "CREATE TABLE literature_document ("
            "id bigint PRIMARY KEY, title text NOT NULL, source text NOT NULL DEFAULT 'pubmed',"
            "abstract text, year int, is_duplicate boolean DEFAULT false, screening_status text,"
            "project_context text DEFAULT 'literev')")
        cur.execute(
            "CREATE TABLE document_chunk ("
            "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "document_id bigint NOT NULL REFERENCES literature_document(id) ON DELETE CASCADE,"
            "chunk_index int DEFAULT 0, content text, chunk_type text, embedding text)")
        cur.execute(
            "CREATE TABLE article_scenarios (scenario_id text, document_id bigint,"
            "similarity_score double precision, screening_status text,"
            "PRIMARY KEY (scenario_id, document_id))")
        cur.execute("SELECT to_regclass('user_scenarios') IS NULL")
        if cur.fetchone()[0]:
            main._ensure_user_scenarios_table()
        cur.execute("SELECT to_regclass('scenario_settings') IS NULL")
        if cur.fetchone()[0]:
            main._ensure_scenario_settings_table()
        cur.execute("DELETE FROM user_scenarios WHERE id = %s", (SID,))
        cur.execute(
            "INSERT INTO user_scenarios (id, name, query, mode, filters, article_count, pipeline_status, populate_status) "
            "VALUES (%s, %s, %s, 'boolean', '{}', 3, 'done', 'done')",
            (SID, "Counts", "influenza AND wastewater"))
        cur.execute(
            "INSERT INTO literature_document (id, title, abstract, is_duplicate) VALUES "
            "(1, 'A', 'abstract one long enough to count', false),"
            "(2, 'B', 'abstract two long enough to count', false),"
            "(3, 'C', 'abstract three long enough to count', false),"
            "(4, 'D', 'a flagged duplicate, never counted', true)")
        cur.execute("INSERT INTO article_scenarios (scenario_id, document_id, similarity_score) VALUES "
                    "(%s, 1, 0.9), (%s, 2, 0.5), (%s, 3, 0.1), (%s, 4, 0.9)", (SID, SID, SID, SID))
        cur.execute("INSERT INTO document_chunk (document_id, content, chunk_type, embedding) VALUES "
                    "(1, 'x', 'title_abstract', '[0.1]'), (2, 'y', 'title_abstract', NULL)")
    main._store_prisma_identification(SID, main._prisma_identification_figures({"db_cache": 3}, 3, 0, 3))
    yield db_conn
    with db_conn.cursor() as cur:
        cur.execute("DELETE FROM user_scenarios WHERE id = %s", (SID,))


def _counts(sid):
    from fastapi.testclient import TestClient
    r = TestClient(main.app).get(f"/user-scenarios/{sid}/counts")
    assert r.status_code == 200, r.text
    return r.json()


def test_the_endpoint_agrees_when_everything_matches(seeded):
    c = _counts(SID)
    assert c["in_progress"] is False
    assert c["corpus_links"] == 3                    # the flagged duplicate is excluded
    assert c["article_count"] == 3 and c["prisma_screened"] == 3
    assert c["above_threshold"] + c["below_threshold"] == 3   # default threshold 0.45: 2 above, 1 below
    assert c["above_threshold"] == 2
    assert c["embedded"] == 1                        # only doc 1 has an embedding
    assert c["consistent"] is True and c["mismatches"] == []


def test_the_endpoint_names_a_stale_stored_count(seeded):
    """The exact production shape: the card's stored copy lags the database."""
    with seeded.cursor() as cur:
        cur.execute("UPDATE user_scenarios SET article_count = 2 WHERE id = %s", (SID,))
    c = _counts(SID)
    assert c["consistent"] is False
    assert c["mismatches"] == [{"field": "article_count", "value": 2, "expected": 3}]


def test_a_stale_search_figure_is_reported_as_drift_not_as_a_mismatch(seeded):
    """The PRISMA panel reconciles the search-time figures with the corpus (the difference
    is shown on its own line), so the banner no longer calls a stale figure a
    disagreement; the raw figure and the drift stay exposed for the audit."""
    main._store_prisma_identification(SID, main._prisma_identification_figures({"db_cache": 1}, 1, 0, 1))
    c = _counts(SID)
    assert c["corpus_links"] == 3
    assert c["prisma_screened"] == 3                      # what the panel shows: the corpus
    assert c["prisma_screened_at_search"] == 1 and c["prisma_drift"] == 2
    assert c["consistent"] is True and c["mismatches"] == []


def test_a_running_pipeline_is_reported_as_in_progress(seeded):
    with seeded.cursor() as cur:
        cur.execute("UPDATE user_scenarios SET pipeline_status = 'running', pipeline_step = 'fulltext' WHERE id = %s", (SID,))
    c = _counts(SID)
    assert c["in_progress"] is True and c["current_step"] == "fulltext"
